package main

func createItem(id string, name string) Item {
	return Item{
		Id:   id,
		Name: name,
	}
}

// new test
func createVegetarianItem(id string, name string) Item {
	return Item{
		Id:         id,
		Name:       name,
		Vegetarian: true,
	}
}

// Based on physical menu
var menu = []Item{
	createItem("1", "Hot & Sour Soup"),
	createItem("2", "Chicken & Sweetcorn Soup"),
	createItem("3a", "Chicken & Noodle Soup"),
	createItem("4", "Sesame Prawn on Toast"),
	createItem("5", "Crispy Seaweed"),
	createItem("5a", "Salt & Pepper Chicken Wings"),
	createItem("6", "Pancake Rolls (1, 2 or 3)"),
	createItem("7", "Prawn Crackers"),
	createItem("7a", "Satay Chicken (5)"),
	createItem("7b", "Smoked Chicken"),
	createItem("8", "Mini Crispy Spring Rolls (8)"),
	createVegetarianItem("8a", "Vegetarian Mini Crispy Spring Rolls (8)"),
	createItem("9", "Assorted Appetizers for One Person"),
	createItem("10", "Assorted Appetizers for Two Persons"),
	createItem("10a", "Crispy Aromatic Lamb"),
	createItem("10c", "Chicken Lettuce Wrap"),
	createItem("11", "Aromatic Crispy Duck"),
	createItem("12", "Roast Duck Cantonese Style"),
	createItem("13", "Roast Duck with Pineapple"),
	createItem("14", "Roast Duck with Mixed Vegetables"),
	createItem("14a", "Roast Duck with Mushrooms"),
	createItem("14b", "Roast Duck in Plumb Sauce"),
	createItem("15", "Satay King Prawns in Spicy Sauce"),
	createItem("16", "Sea-Spicy King Prawns"),
	createItem("17", "Kung Pao Chilli King Prawns"),
	createItem("18", "King Prawns in Chilli Black Bean Sauce"),
	createItem("19", "King Prawns with Bamboo Shoot and Water Chestnuts"),
	createItem("20", "King Prawns with Cashew Nuts"),
	createItem("21", "King Prawns with Cashew Nuts"),
	createItem("22", "King Prawns with Mushrooms"),
	createItem("22a", "Salt & Pepper Chilli Squid"),
	createItem("23", "Satay Chicken Spicy Sauce"),
	createItem("24a", "Chicken in Black Pepper Sauce"),
	createItem("25", "Kung Pao Chilli Chicken"),
	createItem("26", "Chicken in Black Bean Sauce"),
	createItem("27", "Crispy Chicken with Lemon Sauce"),
	createItem("28", "Chicken with Bamboo Shoots and Water Chestnuts"),
	createItem("29", "Chicken With Cashew Nuts"),
	createItem("30", "Chinese Roast Chicken on Bean Sprouts"),
	createItem("31", "Chicken with Pineapples"),
	createItem("32", "Chicken with Mixed Vegetables"),
	createItem("33", "Chicken with Mushrooms"),
	createItem("34", "Chicken in Oyster Sauce"),
	createItem("34b", "Chicken with Cashew Nuts in Yellow Bean Sauce"),
	createItem("35", "Happy Family"),
	createItem("36", "Roast Chicken with Chips"),
	createItem("37", "Crispy Shredded Beef with Chilli"),
	createItem("38", "Satay Beef with Chilli"),
	createItem("39", "Beef in Black Bean Sauce"),
	createItem("40", "Beef with Bamboo Shoots and Water Chestnuts"),
	createItem("41", "Beef Peking Style"),
	createItem("41a", "Beef in Black Pepper Sauce"),
	createItem("42", "Beef with Cashew Nuts"),
	createItem("43", "Beef with Mixed Vegetables"),
	createItem("44", "Beef with Mushrooms"),
	createItem("45", "Beef with Tomatoes"),
	createItem("46", "Ginger & Spring Onion (pork, chicken or beef)"),
	createItem("47", "Chinese Roast Pork on Bean Sprouts"),
	createItem("48", "Chinese Roast Pork with Mushrooms"),
	createItem("48a", "Szechaun Style (pork, chicken or beef)"),
	createItem("49", "Barbequed Spare Ribs (with sauce or dry)"),
	createItem("50", "King Do Spare Ribs with Special Peking Sauce"),
	createItem("50a", "Salt & Pepper Chilli Ribs"),
	createItem("50c", "Salt & Pepper Pork Slice"),
	createItem("51", "Sweet & Sour Chicken (balls)"),
	createItem("52", "Sweet & Sour Chicken Cantonese Style"),
	createItem("53", "Sweet & Sour King Prawn (balls)"),
	createItem("53a", "Sweet & Sour King Prawn Cantonese Style"),
	createItem("54", "Sweet & Sour Pork (balls)"),
	createItem("55", "Sweet & Sour Pork Cantonese Style"),
	createItem("55a", "Sweet & Sour Spare Ribs Cantonese Style"),
	createVegetarianItem("56", "Sweet & Sour Mixed Vegetables"),
	createVegetarianItem("56a", "Sweet & Sour Mushrooms (balls)"),
	createItem("57", "Sweet & Sour Sauce"),
	createItem("58a", "Chop Suey (chicken, beef, king prawn or roast pork)"),
	createVegetarianItem("59a", "Fried Bean Curs in Black Bean Sauce"),
	createVegetarianItem("60a", "Fried Bean Curd in Sweet & Sour Sauce"),
	createItem("61a", "Roast Duck Chop Suey"),
	createItem("62", "Special Shanghai Chop Suey"),
	createItem("64", "Curry Beef"),
	createItem("65", "Curry Chicken"),
	createItem("66", "Curry King Prawn"),
	createItem("67", "Curry Pork"),
	createVegetarianItem("68", "Curry Mixed Vegetable or Mushrooms"),
	createItem("69", "Special Curry"),
	createItem("70", "Curry Sauce"),
	createItem("71", "Shanghai Special Chow Mein"),
	createItem("72", "Beef Chow Mein"),
	createItem("73", "Chicken Chow Mein"),
	createItem("74", "King Prawn Chow Mein"),
	createItem("75", "Roast Pork Chow Mein"),
	createItem("76", "Singapore Chow Mein (spicy)"),
	createItem("76a", "Singapore Vermicelli (spicy)"),
	createVegetarianItem("77", "Mushroom Chow Mein"),
	createVegetarianItem("78", "Plain Chow Mein"),
	createVegetarianItem("78a", "Vegetarian Chow Mein"),
	createItem("79", "House Special Fu Yung or Omelette"),
	createItem("80", "King Prawn Fu Yung or Omelette"),
	createItem("81", "Chicken Fu Yung or Omelette"),
	createVegetarianItem("82", "Plain Fu Yung or Omelette"),
	createVegetarianItem("82a", "Mushroom Fu Yung or Omelette"),
	createItem("83", "Shanghai Fried Rice (extra meat topping, smothered in BBQ sauce)"),
	createItem("84", "Yeung Chow Fried Rice"),
	createItem("85", "Roast Duck & Pork with Fried Rice"),
	createItem("86", "Barbequed Pork & Roast Chicken"),
	createItem("86a", "Spicy Lamb Fried Rice"),
	createItem("87", "Spicy Chicken & Pineapple with Fried Rice"),
	createItem("88", "Chicken Fried Rice"),
	createItem("89", "King Prawn Fried Rice"),
	createItem("91", "Roast Pork Fried Rice"),
	createItem("92", "Singapore Fried Rice (spicy)"),
	createVegetarianItem("93", "Mushroom Fried Rice"),
	createItem("94", "Egg Fried Rice"),
	createVegetarianItem("95", "Plain Boiled Rice"),
	createVegetarianItem("96", "Bamboo Shoots & Water Chestnuts"),
	createVegetarianItem("97", "Bean Sprouts"),
	createVegetarianItem("98", "Mixed Vegetables (fried)"),
	createVegetarianItem("99", "Mixed Vegetables in Chilli Black Bean Sauce"),
	createVegetarianItem("99a", "Sea Spicy Aubergine"),
	createItem("100", "Banana or Pineapple Fritter"),
	createVegetarianItem("102", "Chips"),
	createItem("103", "Barbequed Sauce"),
	createVegetarianItem("104", "Mushrooms"),
	createItem("105", "Sirloin Steak (with peas, mushrooms & chips)"),
	createItem("106", "Chicken Maryland (with peas, mushrooms & chips)"),
	createItem("107", "Happy Children's Meal (nuggets, sausage & chips)"),
	createItem("108", "Satay, Hoi Sin, Soy Sauce"),
}
